version: '3'

services:
  app:
    image: node:14.15.3-alpine
    container_name: insurance-adviser
    restart: always
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
      - "9222:9222"
    working_dir: /app
    entrypoint: ['npm', 'run', 'start:docker-dev']
    volumes:
      - .:/app
    networks:
      - insurance-adviser-network

networks:
  insurance-adviser-network:
    driver: bridge
