module.exports = Object.freeze({
  INSURANCE_ADVICE_CONTROLLER: 'INSURANCE_ADVICE_CONTROLLER',
  GENERATE_INSURANCE_ADVICE_USE_CASE: 'GENERATE_INSURANCE_ADVICE_USE_CASE',
  GENERATE_SCORE_USE_CASE: 'GENERATE_SCORE_USE_CASE',
});
